# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tabuleiro.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class PecaTipo(betterproto.Enum):
    PECA = 0
    PEAO = 1
    DAMA = 2


@dataclass
class Peca(betterproto.Message):
    cor: str = betterproto.string_field(1)
    tipo: "PecaTipo" = betterproto.enum_field(2)


@dataclass
class Posicao(betterproto.Message):
    linha: int = betterproto.int32_field(1)
    coluna: int = betterproto.int32_field(2)


@dataclass
class Tabuleiro(betterproto.Message):
    pecas: List["Peca"] = betterproto.message_field(1)


@dataclass
class MoveRequest(betterproto.Message):
    inicio: "Posicao" = betterproto.message_field(1)
    fim: "Posicao" = betterproto.message_field(2)


@dataclass
class StandardResponse(betterproto.Message):
    message: str = betterproto.string_field(1)
